data_sources:
  test_data:
    enabled: true
    path: data/test.txt
inference:
  beam_size: 5
logging:
  level: INFO
model:
  architecture:
    layer_names:
    - token
    - syntactic
    - semantic
    - discourse
    - pragmatic
    - reasoning
    num_layers: 6
  layers:
    discourse:
      context_window: 10
      hidden_dim: 768
    pragmatic:
      hidden_dim: 512
      intent_classes:
      - question
      - statement
    reasoning:
      hidden_dim: 1024
      max_steps: 10
    semantic:
      entity_types:
      - PERSON
      - ORG
      - LOC
      hidden_dim: 1024
    syntactic:
      attention_heads: 12
      hidden_dim: 768
    token:
      hidden_dim: 768
      vocab_size: 50000
paths:
  data_dir: data/
  log_dir: logs/
  model_dir: models/
system:
  name: HRM
  version: 1.0.0
training:
  data:
    batch_size: 32
    test_split: 0.1
    train_split: 0.8
    val_split: 0.1
  optimizer:
    lr: 0.0001
    type: adamw
